[default]
log_level = "debug"
port = 8080

[default.limits]
file = "128MiB"
data-form = "128MiB"

[default.databases.app_db]
url = "sqlite:db.sqlite"

[debug.webauthn.relying_party]
id = "localhost"
origin = "http://localhost:8080"
name = "TempFiles"

[debug.vite]
type = "Dev"
origin = "http://localhost:5173"

[release.vite]
type = "Release"
root = "www/dist"